--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-09-2023   
--------------------------------------------------------
DROP TABLE "CARMU"."KORFREEBOARD" cascade constraints;
DROP TABLE "CARMU"."MEMBER_TBL" cascade constraints;
DROP TABLE "CARMU"."NOTICE_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table KORFREEBOARD
--------------------------------------------------------

  CREATE TABLE "CARMU"."KORFREEBOARD" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_SUBJECT" VARCHAR2(50 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(2000 BYTE), 
	"NOTICE_WRITER" VARCHAR2(18 BYTE), 
	"NOTICE_DATE" DATE DEFAULT SYSDATE, 
	"NOTICE_GOOD" NUMBER DEFAULT 0, 
	"NOTICE_VIEW" NUMBER DEFAULT 0, 
	"NOTICE_COMMENT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "CARMU"."MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"MEMBER_PW" VARCHAR2(50 BYTE), 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"MEMBER_NICNAME" VARCHAR2(50 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(50 BYTE), 
	"MEMBER_PHONE" VARCHAR2(50 BYTE), 
	"MEMBER_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE_TBL
--------------------------------------------------------

  CREATE TABLE "CARMU"."NOTICE_TBL" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_SUBJECT" VARCHAR2(50 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(1000 BYTE), 
	"NOTICE_WRITER" VARCHAR2(50 BYTE), 
	"NOTICE_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VIEW_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CARMU.KORFREEBOARD
SET DEFINE OFF;
Insert into CARMU.KORFREEBOARD (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,NOTICE_GOOD,NOTICE_VIEW,NOTICE_COMMENT) values (18,'세차 했습니다','날씨가 덥지만 세차 했어요 ㅎ ','admin',to_date('23/08/09','RR/MM/DD'),0,0,0);
Insert into CARMU.KORFREEBOARD (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,NOTICE_GOOD,NOTICE_VIEW,NOTICE_COMMENT) values (20,'세차하니 좋습니다',' 더워도 좋아요 ㅎ','admin',to_date('23/08/09','RR/MM/DD'),0,0,0);
REM INSERTING into CARMU.MEMBER_TBL
SET DEFINE OFF;
Insert into CARMU.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_NICNAME,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_DATE) values ('zkdhk1','85090909','김현우','혀누','zkdhk1@naver.com','01075738416',to_date('23/08/09','RR/MM/DD'));
Insert into CARMU.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_NICNAME,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_DATE) values ('zkdhk123','85090909','냥댕','냥댕','zkdhk12naver.com','01075738416',to_date('23/08/09','RR/MM/DD'));
Insert into CARMU.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_NICNAME,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_DATE) values ('zkdhk123','85090909','냥댕','냥댕','zkdhk12naver.com','01075738416',to_date('23/08/09','RR/MM/DD'));
REM INSERTING into CARMU.NOTICE_TBL
SET DEFINE OFF;
Insert into CARMU.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (6,'두번째 공지',' !! !!!','admin',to_timestamp('23/08/09 02:03:28.901000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/09 02:03:28.901000000','RR/MM/DD HH24:MI:SSXFF'),0);
Insert into CARMU.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (3,'첫번째 공지입니다.!!','첫번째 공지사항입니다.안녕하세요.
카뮤니티입니다.  ','admin',to_timestamp('23/08/09 01:09:59.915000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/09 01:09:59.915000000','RR/MM/DD HH24:MI:SSXFF'),0);
--------------------------------------------------------
--  DDL for Index SYS_C007163
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARMU"."SYS_C007163" ON "CARMU"."KORFREEBOARD" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007161
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARMU"."SYS_C007161" ON "CARMU"."NOTICE_TBL" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table KORFREEBOARD
--------------------------------------------------------

  ALTER TABLE "CARMU"."KORFREEBOARD" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARMU"."KORFREEBOARD" MODIFY ("NOTICE_SUBJECT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE_TBL
--------------------------------------------------------

  ALTER TABLE "CARMU"."NOTICE_TBL" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARMU"."NOTICE_TBL" MODIFY ("NOTICE_WRITER" NOT NULL ENABLE);
  ALTER TABLE "CARMU"."NOTICE_TBL" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CARMU"."NOTICE_TBL" MODIFY ("NOTICE_SUBJECT" NOT NULL ENABLE);
